# Generated by Django 3.0.3 on 2020-10-21 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201021_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountuser',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Debose_and_debit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debose', models.IntegerField()),
                ('debit', models.IntegerField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AmountUser')),
            ],
        ),
    ]
